'use client'
import { useCallback, useEffect, useState } from 'react'
import { deliveryStatus, statusLabels, type CustomerOrder } from '@/lib/customer-types'
import { money } from '@/lib/catalog'
const transitions: Record<string, string[]> = { pending: ['pending', 'processing', 'cancelled'], paid: ['paid', 'processing', 'cancelled'], processing: ['processing', 'shipped', 'cancelled'], shipped: ['shipped', 'out_for_delivery', 'delivered'], out_for_delivery: ['out_for_delivery', 'delivered'], delivered: ['delivered'], cancelled: ['cancelled'], refunded: ['refunded'] }
export function AdminOrders() {
  const [orders, setOrders] = useState<CustomerOrder[]>([]), [error, setError] = useState(''), [loaded, setLoaded] = useState(false)
  const [notice, setNotice] = useState('')
  const refresh = useCallback(async () => { try { const r = await fetch('/api/admin/orders', { cache: 'no-store' }); const data = await r.json(); if (!r.ok) throw Error(data.error); setOrders(data.orders); setError('') } catch (e) { setError((e as Error).message) } finally { setLoaded(true) } }, [])
  // State is updated after the network response, not synchronously in this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void refresh() }, [refresh])
  return <section><div className="mb-5 flex justify-between gap-4"><p>Manage order preparation and customer delivery updates.</p><button onClick={refresh} className="underline">Refresh</button></div><p role="status" className="mb-4">{notice}</p>{error && <p role="alert">{error}</p>}{!loaded ? <p>Loading orders…</p> : !orders.length && !error ? <p>No customer orders yet.</p> : <div className="space-y-6">{orders.map(order => <DeliveryEditor key={`${order.id}:${order.updated_at || order.order_events.length}`} order={order} saved={async () => { setNotice('Delivery update saved. The customer can now see it.'); await refresh() }} />)}</div>}</section>
}
function DeliveryEditor({ order, saved }: { order: CustomerOrder; saved: () => Promise<void> }) {
  const shipment = order.shipments[0], current = deliveryStatus(order)
  const [status, setStatus] = useState(current), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  async function submit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault(); const details = Object.fromEntries(new FormData(e.currentTarget)); setBusy(true); setMessage('')
    try { const r = await fetch('/api/admin/orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: order.id, status, details }) }); const data = await r.json(); if (!r.ok) throw Error(data.error); setMessage('Delivery update saved. The customer can now see it.'); await saved() } catch (e) { setMessage((e as Error).message) } finally { setBusy(false) }
  }
  return <article className="rounded-lg border bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><h2 className="break-all font-semibold">{order.order_number}</h2><span>{statusLabels[current] || current}</span></div><p className="my-3">{order.order_items.map(i => `${i.product_name}, ${i.size} × ${i.quantity}`).join('; ')}</p><p className="text-sm">Items subtotal: {money(Number(order.subtotal), order.currency)} · Placed {order.created_at.slice(0, 10)}</p><p className="my-3 text-sm">{['name', 'email', 'phone', 'address', 'city', 'state', 'country'].map(k => order.shipping_address[k]).filter(Boolean).join(' · ')}</p><p className="mb-5 text-sm text-zinc-600">{order.payments?.some(p => p.status === 'successful') ? `Paystack payment confirmed${order.payments.some(p => p.status === 'successful' && p.provider_mode === 'test') ? ' (TEST: no real money charged)' : ''}.` : 'Payment has not been confirmed.'} Delivery updates do not record payments.</p><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label>Order status<select value={status} onChange={e => setStatus(e.target.value)}>{(order.payment_provider === 'paystack' && current === 'pending' ? ['pending', 'cancelled'] : transitions[current] || [current]).map(s => <option key={s} value={s}>{statusLabels[s] || s}</option>)}</select></label>{[{ name: 'carrier', label: 'Carrier', value: shipment?.carrier }, { name: 'trackingNumber', label: 'Tracking number', value: shipment?.tracking_number }, { name: 'trackingUrl', label: 'Carrier tracking link (HTTPS)', value: shipment?.tracking_url, type: 'url' }, { name: 'location', label: 'Latest delivery location', value: shipment?.current_location }, { name: 'estimatedDelivery', label: 'Estimated delivery date', value: shipment?.estimated_delivery, type: 'date' }].map(field => <label key={field.name}>{field.label}<input name={field.name} type={field.type || 'text'} defaultValue={field.value || ''} maxLength={500} /></label>)}<label className="sm:col-span-2">Update for the customer<textarea name="note" maxLength={1000} placeholder="For example: Your parcel has arrived at the Lagos sorting centre." /></label><button disabled={busy} className="store-primary">{busy ? 'Saving…' : 'Save delivery update'}</button><p role="status">{message}</p></form></article>
}
