'use client'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useState } from 'react'
import { Gem, HelpCircle, LogOut, Menu, MessageSquare, Package, Settings, ShoppingBag, Store, X } from 'lucide-react'
import { useCustomer } from './customer-provider'
import { useCart } from './cart-provider'
const navigation = [['Overview', '/dashboard', Gem], ['Shopping Bag', '/dashboard/cart', ShoppingBag], ['Your Orders', '/dashboard/orders', Package], ['Order Updates', '/dashboard/messages', MessageSquare], ['Account Settings', '/dashboard/account', Settings], ['Visit Shop', '/shop', Store]] as const
export function PatronDashboardShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false); const pathname = usePathname(); const { customer, signOut } = useCustomer(); const { items } = useCart()
  return <div className="min-h-screen bg-[#f4f1eb] text-[#211f1d] lg:pl-[255px]"><button onClick={() => setOpen(true)} aria-label="Open dashboard menu" className="fixed left-4 top-4 z-30 grid h-11 w-11 place-items-center bg-black text-[#e7c451] lg:hidden"><Menu className="h-5 w-5" /></button>{open && <button aria-label="Close dashboard menu" onClick={() => setOpen(false)} className="fixed inset-0 z-40 bg-black/60 lg:hidden" />}<aside className={`fixed inset-y-0 left-0 z-50 flex w-[255px] flex-col overflow-y-auto bg-black px-6 py-8 text-zinc-200 transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><button onClick={() => setOpen(false)} aria-label="Close dashboard menu" className="absolute right-4 top-4 lg:hidden"><X className="h-5 w-5" /></button><Link href="/" className="font-heading text-[27px] text-[#e7c451]">Adire Teems</Link><div className="mt-8"><p className="font-semibold text-white">{customer?.name || 'Welcome, shopper'}</p><p className="mt-1 break-all text-xs text-zinc-400">{customer?.email || 'Your personal shopping space'}</p></div><nav className="-mx-6 mt-8 space-y-1">{navigation.map(([label, href, Icon]) => <Link onClick={() => setOpen(false)} key={href} href={href} aria-current={pathname === href ? 'page' : undefined} className={`flex items-center gap-3 border-l-4 px-6 py-3.5 text-sm font-semibold ${pathname === href ? 'border-[#e7c451] bg-[#24211f] text-[#e7c451]' : 'border-transparent hover:bg-zinc-900'}`}><Icon className="h-5 w-5" />{label}{href === '/dashboard/cart' && <span className="ml-auto">{items.reduce((n, i) => n + i.quantity, 0)}</span>}</Link>)}</nav><div className="mt-auto space-y-5 pt-10 text-sm"><Link href="/contact" className="flex items-center gap-3"><HelpCircle className="h-5 w-5" />Customer support</Link>{customer && <button onClick={signOut} className="flex items-center gap-3"><LogOut className="h-5 w-5" />Sign out</button>}</div></aside><section className="min-w-0 px-6 py-20 sm:px-10 lg:px-12 lg:py-10">{children}</section></div>
}
