'use client'
import Link from 'next/link'
import { DashboardHeader, Title } from '@/components/dashboard-ui'
import { useCustomer } from '@/components/customer-provider'
import { useCart } from '@/components/cart-provider'
import { useStore } from '@/components/store-provider'
import { useCurrency } from '@/components/currency-provider'
import { OrderList } from '@/components/customer-orders'
export default function DashboardPage() {
  const { customer, error } = useCustomer(); const { items, ready, update, syncError, retrySync } = useCart(); const { products } = useStore(); const { money } = useCurrency()
  const count = items.reduce((sum, item) => sum + item.quantity, 0)
  return <><DashboardHeader title={customer?.name ? `Welcome, ${customer.name.split(' ')[0]}` : 'Your dashboard'} />{error && <p role="alert" className="mt-4">{error}</p>}<div className="my-8 grid gap-4 sm:grid-cols-3">{[[`${count} items in your bag`, '/dashboard/cart'], ['Orders & delivery tracking', '/dashboard/orders'], ['Explore the shop', '/shop']].map(([label, href]) => <Link key={href} href={href} className="rounded-lg border border-zinc-300 bg-white p-5 font-semibold">{label} →</Link>)}</div><div className="grid gap-8 xl:grid-cols-2"><section><Title title="Your shopping bag" link="View bag" href="/dashboard/cart" />{syncError && <p role="alert" className="mb-4 text-sm">{syncError} <button onClick={retrySync} className="underline">Retry sync</button></p>}{!ready ? <p>Loading your bag…</p> : !items.length ? <div className="rounded-lg border border-dashed border-zinc-400 p-8"><p>Your bag is empty. Items you add in the shop appear here.</p><Link href="/shop" className="mt-4 inline-block underline">Find your next piece</Link></div> : <div className="rounded-lg border border-zinc-300 bg-white p-5">{items.map(item => { const product = products.find(p => p.id === item.productId); return <article key={`${item.productId}-${item.size}`} className="flex gap-4 border-b border-zinc-200 py-4">{product && <Link href={`/product/${product.slug}`}><img src={product.image} alt={product.name} className="h-24 w-20 rounded object-cover" /></Link>}<div className="min-w-0 flex-1">{product ? <Link href={`/product/${product.slug}`} className="font-semibold">{product.name}</Link> : <p>Product no longer available</p>}<p className="my-2 text-sm">Size {item.size} · Qty {item.quantity}</p>{product && <p className="text-sm">{money(product.price * item.quantity, product.currency)}</p>}<button onClick={() => update(item.productId, item.size, 0)} className="mt-2 text-xs underline">Remove</button></div></article> })}<Link href="/checkout" className="mt-5 block bg-black px-5 py-3 text-center text-white">Continue to checkout</Link></div>}</section><section><Title title="Your orders" link="View all" href="/dashboard/orders" /><OrderList limit={3} /></section></div><section className="mt-8 rounded-lg bg-black p-6 text-white"><h2 className="font-heading text-2xl">Follow your order, every step of the way</h2><p className="my-3 text-zinc-300">Open an order to see preparation, dispatch, the latest delivery location, and arrival updates.</p><Link href="/contact" className="text-[#e4c158] underline">Get help with an order</Link></section></>
}
